server:
  port: 8001


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      # 集群版-
        defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    # 服务实例id
    instance-id: order8001
    #访问路径可以显示IP地址
    prefer-ip-address: true


spring:
  application:
    # 微服务名称
    name: orderService
  zipkin:
    # 配置zipkin的服务地址
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      # 跟踪信息收集采样比例，默认 0.1，为 1 是即 100%，收集所有，默认0.1(即10%)
      probability: 1
      # 每秒速率，即每秒最多能跟踪的请求，rate 优先，默认是10
      rate: 20

### 全局Ribbon 配置
ribbon:
  #启用rest client配置
  restclient:
    enabled: true
  # http建立socket超时时间,毫秒，默认是1000
  ConnectTimeout: 1000
  # http读取响应socket超时时间，默认是1000毫秒
  ReadTimeout: 5000
  # 同一台实例最大重试次数,不包括首次调用，默认是1
  MaxAutoRetries: 0
  # 重试负载均衡其他的实例最大重试次数,不包括首次server
  MaxAutoRetriesNextServer: 0