server:
  port: 6001

eureka:
  instance:
    hostname: gateway
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      # 集群版-
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

logging:
  level:
#    调整 gateway 包的 log 级别，以查看 Gateway 相关的日志
    org.springframework.cloud.gateway: debug

spring:
  application:
    name: gateway
  zipkin:
    # 配置zipkin的服务地址
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      # 跟踪信息收集采样比例，默认 0.1，为 1 是即 100%，收集所有，默认0.1(即10%)
      probability: 1
      # 每秒速率，即每秒最多能跟踪的请求，rate 优先，默认是10
      rate: 20

  cloud:
    gateway:
      routes:
        # 路由配置
        - id: payment_route
          # 转发到 http://localhost:9001
#          uri: http://localhost:9001
          # lb协议，负载均衡，轮询转发到
          uri: lb://paymentService
          predicates:
            # 断言，匹配路径 /payment/**
            - Path=/payment/**
          filters:
            # 不管请求路径是什么，固定转发路径为 /payment/get/2 的Filter
            # 配置自定义GateWayFilter
            - name: FixedPathGateWayFilter

      # 开启根据 serviceId 转发，负载均衡也生效
      discovery:
        locator:
          enabled: true
          # route ID 转化小写
          lower-case-service-id: true