

spring:
  application:
    # 服务名称
    name: service-consumer
  cloud:
    nacos:
      discovery:
        # Nacos 注册中心配置地址
        server-addr: 192.168.42.51:8848
        # Nacos 客户端认证信息（默认用户名和密码均为 nacos)
        username: nacos
        password: nacos

management:
  endpoints:
    web:
      exposure:
        # 激活 Spring Boot Actuator Endpoints
        include=*:

server:
  # 应用服务端口
  port: 8080